# Generated by Django 3.2.16 on 2025-02-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationaccount',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='email_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organisationpending',
            name='email_user',
            field=models.IntegerField(null=True),
        ),
    ]
