# Generated by Django 3.2.16 on 2025-02-19 03:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, editable=False, null=True)),
                ('file_group', models.IntegerField(blank=True, choices=[(1, 'Identification'), (2, 'Senior Card')], null=True)),
                ('file_group_ref_id', models.IntegerField(blank=True, null=True)),
                ('extension', models.CharField(blank=True, max_length=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'accounts_privatedocument',
                'managed': False,
            },
        ),
    ]
