# Generated by Django 3.2.16 on 2025-02-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_privatedocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateDocument',
        ),
    ]
