# Generated by Django 4.2.20 on 2025-03-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_delete_privatedocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='group',
        ),
        migrations.AlterField(
            model_name='application',
            name='beverage',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='byo_alcohol',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='food',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='jetty_dot_approval',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='liquor_licence',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='river_lease_require_river_lease',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='river_lease_reserve_licence',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
