# Generated by Django 4.2.20 on 2025-05-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0017_rename_prevent_auto_locked_systemuser_prevent_auto_lock'),
        ('applications', '0005_application_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_group_assignment', to='ledger_api_client.systemgroup'),
        ),
    ]
