sudo: false
language: python
cache: pip
python:
    - "3.8"
addons:
    postgresql: "9.6"
services:
    - postgresql
branches:
    only:
        - master
env:
    global:
        - SECRET_KEY=SecretKeyForTravis
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
        - PRODUCTION_EMAIL=False
        - EMAIL_INSTANCE="TEST"
        - NON_PROD_EMAIL="travis@dpaw.wa.gov.au"
        - BPAY_ALLOWED=True
        - EMAIL_FROM="no-reply@dbca.wa.gov.au"
        - DEBUG=True
sudo: true
install:
    - sudo apt-get install postgresql-9.6-postgis-2.4 -y -q
    - pip install pip --upgrade
    - pip install -r requirements.txt
before_script:
    - touch .env
    - psql -c 'create database travis_ci_test;' -U postgres
    - python manage.py migrate --noinput
script:
    - python manage.py test statdev

