sudo: false
language: python
cache: pip
dist: focal
python:
    - "3.8"
addons:
    postgresql: "13"
    apt:
      packages:
         - postgis
         - postgresql-13-postgis-3
         - postgresql-13-postgis-3-scripts
         - postgresql-client-13
services:
    - postgresql
branches:
    only:
        - master
env:
    global:
        - ALLOWED_DOMAIN="*"
        - SECRET_KEY=SecretKeyForTravis
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
        - PRODUCTION_EMAIL=False
        - EMAIL_INSTANCE="TEST"
        - NON_PROD_EMAIL="travis@dpaw.wa.gov.au"
        - BPAY_ALLOWED=True
        - EMAIL_FROM="no-reply@dbca.wa.gov.au"
        - DEBUG=True
sudo: true
install:
    - sudo apt-get install postgresql-13 postgresql-13-postgis-3 postgresql-client-13 postgresql-13-postgis-3-scripts -y -q
    - pip install pip --upgrade
    - pip install --upgrade setuptools
    - pip install six
    - pip install -r requirements.txt
before_script:
    - touch .env
    - sudo /etc/init.d/postgresql restart
    - psql --version
    - psql -c 'create database travis_ci_test;' -U postgres
    - psql -U postgres -c "create extension postgis"
    - python manage.py migrate --noinput
script:
    - python manage.py test statdev
