# Generated by Django 3.2.16 on 2025-02-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='applicant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
